### ISSUE TITLE
[BUG] Registros 1100 e 1500 do Sped Contribuições

### ISSUE THREAD

**Issue by WandersonLSoft** [orochasamuel/fiscalbr-net#116]
Registro 1100 
   campo CNPJ_SUC   está como decimal 
   campo COD_CRED está como decimal  

Registro 1500 
   campo CNPJ_SUC   está como decimal 
   campo COD_CRED está como decimal  
   campo 17 - VL_CRED_OUT ( está com o nome incorreto VlBcPisSusp, seguindo o padrão do registro 1100 deveria ser VlCredOut)

Os demais campos númericos desses registros, estão como string.

Fiz os tratamentos e está gerando de forma correta agora.
Favor validar as alterações que realizei.

**Comment by orochasamuel** [comment]
Correções feitas no commit https://github.com/orochasamuel/fiscalbr-net/commit/3849b7221aebbe3dceeeabc8031cd7ea6408cb23. o/
