### ISSUE TITLE
[DÚVIDA] Evento "AoProcessarLinha" 

### ISSUE THREAD

**Issue by davi-barboza** [orochasamuel/fiscalbr-net#118]
**Evento não dispara**
Ao tentar utilizar o evento "AoProcessarLinha" juntamente com outro metodo percebi que ele não é disparado em nenhum momento, ele só é chamado no metodo "AoProcessarLinhaRaise" e este não é chamado em nenhum outro lugar.

**Dúvida**
Cheguei nessa dúvida durante uma busca em remover os pipes( | ) das strings após as atribuições de todos os blocos. Gostaria de saber exatamente qual a finalidade desse evento, talvez nem sirva para o que estou fazendo mas me gerou essa dúvida.

**Screenshots**
![image](https://github.com/orochasamuel/fiscalbr-net/assets/67708096/2d693274-45f0-49e3-949a-572f0b9e5a8b)

**Ambiente**
 - Layout: [ SPED Fiscal]

**Possível Feature**
Seria interessante se a biblioteca removesse todos os pipes das strings automaticamente, visto que ele é um separador de registros do sped.

**Comment by marcosgerene** [comment]
@davi-barboza 

O evento ao processar linha foi criado por mim. Uso ele na leitura do arquivo.

![image](https://github.com/orochasamuel/fiscalbr-net/assets/15945003/78c70777-e92a-45e7-9b83-680ffa09dc06)

Aqui eu uso para saber qual linha estou lendo no momento para gerar uma espécie de "barra de progresso" na leitura de arquivos grandes.


@orochasamuel não se trata de um bug.
