### ISSUE TITLE
Duvidas fiscalbr-net

### ISSUE THREAD

**Issue by Pcgaspar** [orochasamuel/fiscalbr-net#123]
Estou precisando gerar os arquivos fiscais digitais exigidos , detalhe não tenho muito conhecimento com o TypeScript !!!

**Comment by orochasamuel** [comment]
Fala @Pcgaspar tudo na paz?

Aqui na lib .NET você consegue gerar os arquivos, dá uma olhada na issue https://github.com/orochasamuel/fiscalbr-net/issues/41, se tiver alguma dúvida adicional é só postar aqui.

Já no caso da lib JS, ainda está em fase "embrionária", não sendo possível gerar os arquivos ainda. Não tenho muita expertise com Javascript então, estava codando em um ritmo menor.

Vida longa e próspera  🖖
