### ISSUE TITLE
[BUG] Bloco D500 - Alguém teve esse problema?

### ISSUE THREAD

**Issue by EduardoVazOliveira** [orochasamuel/fiscalbr-net#124]
**Descreva o erro**
Está gerando erro no tamanho dos campos 22 para 24

**Screenshots**
![image](https://github.com/orochasamuel/fiscalbr-net/assets/19534443/83788c42-9395-461d-ad27-141ddbbc3292)

**Ambiente**
 - Layout: SPED Fiscal
 - Versão .NET framework 4.8
![image](https://github.com/orochasamuel/fiscalbr-net/assets/19534443/62764806-963e-4e47-a0fa-8f874d8e8f42)

**Comment by orochasamuel** [comment]
Fala @EduardoVazOliveira tudo na paz?

Conseguiu resolver? 

O problema era na versão da lib ou na versão do PVA?

Vida longa e próspera 🖖

**Comment by EduardoVazOliveira** [comment]
Opa boa tarde!

Consegui, era cagada minha mesmo, estava gerando com o objeto do
contribuições tinha copiado e não percebi kk.
Ajustei e gerou coreto.

Debugando acabei notando o erro.

Obrigado, pelo apoio.

Abrs


Eduardo Vaz de Oliveira
Developer .Net / Web

Celular: (16) 99287-9054
E-mail:   ***@***.***


Em qua., 6 de mar. de 2024 às 14:42, O Samuel Rocha <
***@***.***> escreveu:

**Comment by orochasamuel** [comment]
Fico feliz que tenha resolvido.

Qualquer dúvida adicional é só mandar aqui.
