### ISSUE TITLE
Numero total de Linhas por Registro

### ISSUE THREAD

**Issue by EdsonRodrigoBA** [orochasamuel/fiscalbr-net#125]
**Descreva o erro**
Existe uma forma de preencher os registro totalizadores de cada registro Pai pela biblioteca ou devo fazer os count na lista ? 
Ex: 0990,  B990

**Comment by orochasamuel** [comment]
Fala @EdsonRodrigoBA tudo na paz?

Dá uma olhada na issue https://github.com/orochasamuel/fiscalbr-net/issues/41

Lá tem 2 exemplos de como gerar o arquivo, se você quer que a lib popule automaticamente com a quantidade de linhas use o "ArquivoEFDFiscal" (se for para EFD Fiscal).

Vida longa e próspera 🖖
