### ISSUE TITLE
Numero totalizador de linhas de cada registro

### ISSUE THREAD

**Issue by EdsonRodrigoBA** [orochasamuel/fiscalbr-net#126]
Existe uma forma de preencher os registro totalizadores de cada registro Pai pela biblioteca ou devo fazer os count na lista ?
Ex: 0990, B990

**Comment by orochasamuel** [comment]
Fala @EdsonRodrigoBA tudo na paz?

Dá uma olhada na issue https://github.com/orochasamuel/fiscalbr-net/issues/41

Lá tem 2 exemplos de como gerar o arquivo, se você quer que a lib popule automaticamente com a quantidade de linhas use o "ArquivoEFDFiscal" (se for para EFD Fiscal).

Vida longa e próspera 🖖

**Comment by orochasamuel** [comment]
@EdsonRodrigoBA conseguiu esclarecer a dúvida?

Há algo mais em que eu possa te ajudar?

**Comment by EdsonRodrigoBA** [comment]
Opa, cara acho que escrevi errado:
A minha duvida é se consigo preencher esses registro totalizadores usando a biblioteca, sem fazer essa implementação aqui abaixo, que ficou bem verbosa:
![image](https://github.com/orochasamuel/fiscalbr-net/assets/16749983/b143c03a-c022-4f4a-819b-e9106a514187)

Ja estou preenchendo os dados do arquivo:
![image](https://github.com/orochasamuel/fiscalbr-net/assets/16749983/32264e08-9ff7-4b80-b021-3d8970fd6445)
![image](https://github.com/orochasamuel/fiscalbr-net/assets/16749983/f807cb2d-6cbb-4b60-9e9f-c2009daa2289)

**Comment by orochasamuel** [comment]
Experimente usar conforme esse exemplo:

```csharp

            var sped = new ArquivoEFDFiscal();

            if (sped.Bloco0 is null)
                sped.Bloco0 = new FiscalBr.EFDFiscal.Bloco0();

            var reg0000 = new EFDFiscal.Bloco0.Registro0000
            {
                CodVer = Common.CodigoVersaoLeiaute.V15,
                CodFin = Common.IndCodFinalidadeArquivo.RemessaArquivoOriginal,
                DtIni = initialDate,
                DtFin = finalDate,
                Nome = "BANCO DO BRASIL S.A.",
                Cnpj = "00000000000191",
                Uf = "GO",
                Ie = "123456789",
                CodMun = "5204508",
                IndPerfil = Common.IndPerfilArquivo.A,
                IndAtiv = Common.IndTipoAtividade.Outros
            };

            sped.Bloco0.Reg0000 = reg0000;

            sped.GerarLinhas();

            sped.Escrever(@"C:\Users\orochasamuel\Documents\fiscalbr-test.txt");

```

PS: O método `GerarLinhas()` só deve ser utilizado uma única vez logo após popular os registros com as informações do seu sistema.

Vida longa e próspera 🖖

**Comment by orochasamuel** [comment]
@EdsonRodrigoBA conseguiu testar?

Se você usar o método "GerarLinhas()" não precisa preencher manualmente cada totalizador de bloco.

Vida longa e próspera 🖖

**Comment by orochasamuel** [comment]
@EdsonRodrigoBA irei fechar essa issue pois acredito que sua dúvida tenha sido respondida com o exemplo prático fornecido acima.

Caso ainda tenha dúvidas é só reabrir esta ou criar uma nova issue.

Vida longa e próspera 🖖
