### ISSUE TITLE
Tamanho do campo zerado - Registro 1350

### ISSUE THREAD

**Issue by davi-barboza** [orochasamuel/fiscalbr-net#127]
**Descrição do erro**
Os campos "SERIE" e "MODELO" do registro 1350 (EFD-fiscal) não estão sendo gravados no arquivo, acredito que é devido ao tamanho do campo estar zerado.

**Comportamento esperado**
Gravar os campos corretamente no arquivo.

**Screenshots**
![image](https://github.com/orochasamuel/fiscalbr-net/assets/67708096/ad0162b2-09f9-4a75-a4c3-bc16c772be9d)

**Informações adicionais**
Se puderem ajustar o quanto antes agradeço.

**Comment by orochasamuel** [comment]
Fala @davi-barboza tudo na paz?

Correção feita no commit https://github.com/orochasamuel/fiscalbr-net/commit/8c3be02addb8d9611c459a95a5fb5f2300e3e52b.

Vida longa e próspera 🖖

**Comment by davi-barboza** [comment]
Tudo certo meu querido, obrigado pela atenção.

**Comment by orochasamuel** [comment]
Eu quem agradeço por avisar. 

Qualquer dúvida adicional é só falar.

Vida longa e próspera 🖖
