### ISSUE TITLE
SPED EFD Contribuições - ReceitaBX

### ISSUE THREAD

**Issue by luanlopez** [orochasamuel/fiscalbr-net#130]
Bom dia Samuel, beleza?

Talvez não esteja no teu projeto mas, estou precisando fazer uma integração com a API do ReceitanetBX, é do seu conhecimento está API? Se sim, teria ideia de como achar a documentação dela?

**Comment by jvrodrigs** [comment]
Olá! Tudo bem?

Sei que faz muito tempo, mas você teve algum achado sobre a documentação? Estou precisando de mais informações e não consigo achar, por enquanto, nada sobre.

Fico no aguardo! =)

**Comment by orochasamuel** [comment]
Fala @jvrodrigs tudo em paz?

Rapaz, essa documentação aparentemente não está disponível de forma pública, encontrei 3 links, sobre o manual do ReceitaNetBX e duas reclamações no ReclameAqui exatamente sobre a solicitação da documentação técnica da API.

[Manual ReceitaNetBX](https://servicos.receita.fazenda.gov.br/publico/programas/ReceitanetBX/Servicos/manual_servico_receitanetbx.pdf)

[ReclameAqui 1](https://www.reclameaqui.com.br/serpro/solicitacao-de-documentacao-da-api-e-web-service-do-receitanet-bx-para-download-de-arquivos-sped_Vrmz_vt4ZUj04CYY/)

[ReclameAqui 2](https://www.reclameaqui.com.br/serpro/solicitacao-de-acesso-a-documentacao-da-api-receitanetbx-para-download-de-arquivos-sped_McB_TkG9-1x1Oksi/)

Não sei se vai te ajudar mas, se conseguir a documentação técnica pode retornar nessa issue e postar aqui?

**Comment by jvrodrigs** [comment]
Por incrível que pareça, são os mesmos links que abri! kkkkk

Fiz a mesma coisa, fiz um post no reclame aqui e estou na espera da mesma resposta e envio para o e-mail!

Caso tenha resposta, atualizo aqui.

**Comment by guilhermegriloamorim** [comment]
Ja tentei usar o ReceitaBx serviço, mas também não rolou! Acho que eles não irão disponibilizar ainda mais com a RTC.

**Comment by beatriz-ngomes** [comment]
Teve alguma atualização referente a essa issue?

**Comment by luanlopez** [comment]
@orochasamuel  Fala mano, beleza? 

Ainda estou tentando localizar essa documentação (tudo que é referente ao gorverno é um lixo). Você conseguiu obter algo pelo Reclame Aqui ou ainda não?

**Comment by orochasamuel** [comment]
Fala @luanlopez tudo em paz?

Não, infelizmente não. Esse sistema é antigo, acho que nem tem documentação direito OU é somente para uso interno do GOV mesmo.

**Comment by orochasamuel** [comment]
@jvrodrigs teve algum retorno na sua solicitação?

**Comment by jvrodrigs** [comment]
Bom dia, pessoal. 

Obtive retorno no _ReclameAqui_. Porém, foi uma "documentação" meio rasa. Eles disponibilizaram a doc, mas foi realmente só os métodos e o que pode ser consultado.

Esperava algo melhor e principalmente com o que há de disponível de URL na API. 

Não sei se devo disponibilizar aqui diretamente. Mas, se quiserem, posso enviar para o e-mail de vocês que está no **perfil do Github**.

E, também, se alguém tiver alguma informação da própria API (url's) e puder disponibilizar.

**Comment by orochasamuel** [comment]
Opa!! 

Alguma informação é melhor que nenhuma. Fiquei surpreso que eles realmente tenham enviado algo.

@jvrodrigs me envia por favor, meu e-mail aqui no git é samuelro.net@gmail.com

**Comment by jvrodrigs** [comment]
@orochasamuel Enviado!

**Comment by luanlopez** [comment]
Fala mestre @jvrodrigs,

consegue compartilhar comigo também? 

**Email:** luanlopesdasilva165@gmail.com

**Comment by jvrodrigs** [comment]
@luanlopez Encaminhado!

**Comment by luanlopez** [comment]
@jvrodrigs A doc lá mostra os recursos e etc, mas tu sabe me dizer se tem a URL que eu posso usar para chamar isso aqui?

**Comment by jvrodrigs** [comment]
@luanlopez 

Justamente a mesma dor que relatei no meu [comentário](https://github.com/orochasamuel/fiscalbr-net/issues/130#issuecomment-4142069230). Eles falam que é necessário entrar em contato com a Receita Federal. Não obtive exito neste contato.

**Comment by erieridev-beep** [comment]
Oi, @jvrodrigs! Tudo bem?
Pode enviar a documentação do ReceitanetBX para mim também? 🥹

**Comment by luanlopez** [comment]
@erieridev-beep e ai bro, me passa seu e-mail

**Comment by erieridev-beep** [comment]
eri.eri.dev@gmail.com
Obrigada!

**Comment by erieridev-beep** [comment]
Oi, @luanlopez! Tudo bem?
Pode enviar para mim? eri.eri.dev@gmail.com
Obrigada!

**Comment by jezer-lopes** [comment]
@jvrodrigs e @luanlopez 
Tudo bem?

Pode enviar também para mim no jezer.lopes@hotmail.com

Valeu!

**Comment by josimarconnect-crypto** [comment]
Alguém que possui a documentação pode mandar josimarconnect@gmail.com
