### ISSUE TITLE
[BUG] EFD Contribuições - Bloco M215 e M615 - campo VlAjBc com tipo errado (string)

### ISSUE THREAD

**Issue by Crovadore** [orochasamuel/fiscalbr-net#137]
O campo VlAjBc nos blocos M215 e M615 é do tipo decimal, mas está declarado como string. Com isso, não gera corretamente o campo.

**Comment by orochasamuel** [comment]
Fala @Crovadore, tudo em paz?

Obrigado por avisar. o/

Correção no commit https://github.com/orochasamuel/fiscalbr-net/commit/299cecb4ae1aa3689d3cc7bad1920ed87910fba5.

Vida longa e próspera 🖖
