### ISSUE TITLE
DLL usando BD de apoio

### ISSUE THREAD

**Issue by leandrossantos** [orochasamuel/fiscalbr-net#22]
E ai meu amigo @osamueloliveira 
E aquela ideia que lhe dei da API usar um BD de apoio para geração dos arquivos, a aplicação alimenta essa base de dados e então a API gera os arquivos mediante os dados que estiverem no BD.
Vai ter essa opção na API ou não ?

**Comment by orochasamuel** [comment]
Fala @leandrossantos depois de tanto tempo vou retomar esse assunto.

A ideia do banco "separado" é para facilitar a escrita do arquivo? Mas quais informações seriam interessantes serem guardadas nesse banco separado e não no banco de dados do seu cliente?

@adrianotrentim @marcosgerene conseguem enxergar aproveitamento nesse recurso?

Se isso chegar a ser criado seria em uma lib à parte ( **FiscalBr.Data** - por exemplo ), poderia usar SQLite (SQL) ou LiteDB (NOSQL).

**Comment by marcosgerene** [comment]
@orochasamuel 

Tecnicamente o arquivo final (arquivo texto), uma vez que pode ser tanto lido quanto exportado já faz o serviço de armazenagem da informação...

**Comment by orochasamuel** [comment]
Concordo.
