### ISSUE TITLE
Versões Layout

### ISSUE THREAD

**Issue by bruno-crr** [orochasamuel/fiscalbr-net#32]
Bom dia, a biblioteca suporta a geração de arquivos retroativos?
Eu vi que passo o layout para o método de abertura , mas ele vai gerar os arquivos de acordo com a versão informada?

**Comment by marcosgerene** [comment]
@bruno-crr 

É uma excelente ideia, mas infelizmente não é levado em consideração pelo projeto. 

Não sei o @osamueloliveira, mas eu hoje não tenho essa necessidade (como tive com a leitura), então não pretendo implementar nem mesmo a longo prazo.

**Comment by bruno-crr** [comment]
Bom dia, entendi, to precisando implementar uma ferramenta de geração de SPED, mas temos muitos casos onde os clientes necessitam gerar o arquivo em algum Layout específico por conta de notificação do fisco.

**Comment by osamueloliveira** [comment]
Fala @bruno-crr tudo na paz?

Cara... o que dá pra fazer é o seguinte, alterar a lib pra gerar de acordo com a versão que você escolher. Mas os registros mais novos, dos novos layouts serão gerados. Eu já tinha pensado em fazer algo relacionado a isso mas como não havia demanda não mexi com nada. Uma ideia é criar um atributo de data que seria verificado em cada propriedade no ato de geração, a problemática disso aqui é que teria um atributo para cada versão de layout e deixaria a tarefa de mapeamento das classes muito mais "chata", levando em conta que hoje temos 14 versões de layout para a EFD ICMS/IPI.

![image](https://user-images.githubusercontent.com/15462690/122412787-4070b080-cf5c-11eb-814b-7a9261861a84.png)

Vou pensar em algo (aceito sugestões) mais pra frente e retorno nesta issue. Vou deixar aberta enquanto isso.

Vida longa e próspera. 🖖

**Comment by RaCastroBR** [comment]
Boa noite @orochasamuel.

Esse assunto evoluiu? Conseguiu fechar o versionamento?

Obrigado

**Comment by candinho1987** [comment]
Boa noite, para leitura de arquivo de versão anterior tem como informar o "CodigoVersaoLeiaute.V15" por exemplo

**Comment by orochasamuel** [comment]
@RaCastroBR vou retomar a verificação dessas versões do layout e criar alguns testes.

@candinho1987 para a leitura do layout "versionado" não foi feita a implementação ainda, quem fez as features de leitura foi o @marcosgerene e a equipe dele.

Vou trabalhar na lib para chegarmos em uma versão estável no que diz respeito à geração retroativa das informações.

**Comment by marcosgerene** [comment]
@orochasamuel 

Posso estar enganado, mas acredito que para a leitura acho que o versionamento não faz diferença. Uma vez que o arquivo já está gerado, se determinado registro ou campo não existia na versão anterior ele vai ser desconsiderado/marcado como nulo.


Se tiver algum arquivo antigo ai e quiser que eu ajuste algo na leitura nesse sentido me chama no WhatsApp.

Valeu.

**Comment by orochasamuel** [comment]
> @orochasamuel
> 
> Posso estar enganado, mas acredito que para a leitura acho que o versionamento não faz diferença. Uma vez que o arquivo já está gerado, se determinado registro ou campo não existia na versão anterior ele vai ser desconsiderado/marcado como nulo.
> 
> Se tiver algum arquivo antigo ai e quiser que eu ajuste algo na leitura nesse sentido me chama no WhatsApp.
> 
> Valeu.

@marcosgerene a issue #53 relata algumas dificuldades de ser ler arquivos antigos.

**Comment by marcosgerene** [comment]
@orochasamuel 

Se me arrumar um arquivo antigo com esse problema posso tentar arrumar, me manda no whatsapp ou e-mail o arquivo que vejo!

**Comment by orochasamuel** [comment]
Pessoal,

Na issue #109 descrevi a implementação inicial da detecção de versão para a EFD Fiscal. 

Se esse assunto voltar a ser necessário e melhor iniciar uma nova issue.

Vida longa e próspera 🖖
