### ISSUE TITLE
Referencia ao tipo "ArquivoSped" declara que ele é definido em "FiscalBr.Common", mas não pode ser encontrado).  Alguém sabe o que pode ser, ou esta tendo o mesmo problema.

### ISSUE THREAD

**Issue by mdantasgyn** [orochasamuel/fiscalbr-net#33]
Estou tendo problemas com o componente ao estanciar. (Referencia ao tipo "ArquivoSped" declara que ele é definido em "FiscalBr.Common", mas não pode ser encontrado).  Alguém sabe o que pode ser, ou esta tendo o mesmo problema.

**Comment by marcosgerene** [comment]
Bom dia @mdantasgyn 

Acabei de mandar um PR, provavelmente, o projeto estão fazendo um RebuildAll com sucesso e todos os testes estão passando.

Por favor, atualize seu código e tente novamente.

**Comment by marcosgerene** [comment]
![image](https://user-images.githubusercontent.com/15945003/121034033-14e30e80-c783-11eb-93af-0b1659f15afc.png)

**Comment by osamueloliveira** [comment]
Fala @mdantasgyn tudo na paz?

Ainda com problemas?

Vida longa e próspera. 🖖

**Comment by EdsonRodrigoBA** [comment]
Eu tive esse problema, estava tentando usar o projeto via nuget.
Caso esteja tentando usar via nuget vai ter esse erro.
Recomendo baixar o projeto e importar as dll que vai funcionar.

**Comment by leandrossantos** [comment]
Acredito que eu esteja com o problema bem parecido, veja o que acontece na imagem abaixo.
Não consigo usar conforme o exemplo

![Screenshot_340](https://user-images.githubusercontent.com/6373944/125333813-0dce9380-e321-11eb-90b5-97fe036a89af.png)

**Comment by marcosgerene** [comment]
@EdsonRodrigoBA talvez seja questão do @orochasamuel soltar uma versão do Nuget.

@orochasamuel me chama no wpp, se eu tiver permissão no nuget resolvo isso, valeu

**Comment by orochasamuel** [comment]
@marcosgerene acabei de publicar as novas versões no Nuget com as implementações recentes suas e de sua equipe.

@EdsonRodrigoBA @mdantasgyn se vocês puderem validar lhes serei grato.

Os pacotes Nuget estão atualizados com o repositório, mudei as versões para ter um "ponteiro" histórico disto. Nas próximas versões estarei trabalhando de forma mais ativa na lib e agradeço se puderem ajudar reportando melhorias e bugs.

Vida longa e próspera. 🖖
