### ISSUE TITLE
Leitura de Arquivo SPED

### ISSUE THREAD

**Issue by EdsonRodrigoBA** [orochasamuel/fiscalbr-net#38]
Consigo ler um arquivo txt do sped e fazer importação no BD com essa biblioteca?

**Comment by osamueloliveira** [comment]
Fala @EdsonRodrigoBA tudo na paz?

Essa implementação já começou a ser feita mas ninguém (que eu saiba) está usando em produção.

Vida longa e próspera. 🖖

**Comment by EdsonRodrigoBA** [comment]
Ao tentar ler um arquivo:

          var sped = new ArquivoEFDFiscal();
                    sped.Ler(arq.FullName, null);
                    
O objeto de tipo 'System.String' não pode ser convertido no tipo 'System.Nullable`1[FiscalBr.Common.IndPeriodoApuracaoIpi]'.

**Comment by orochasamuel** [comment]
@EdsonRodrigoBA pode me enviar o arquivo que você está tentando ler?

Vida longa e próspera. 🖖

**Comment by orochasamuel** [comment]
Fala @uareke blz?

Esse campo `IndPeriodoApuracaoIpi` já foi alterado de `Nullable` para normal.

Se for no C170 já foi alterado, não encontrei nenhuma outra referência no layout.

Vida longa e próspera 🖖

**Comment by orochasamuel** [comment]
Encerrando... esse bug já foi corrigido.
