### ISSUE TITLE
Tem algum projeto demo? que mostre como usar os métodos?

### ISSUE THREAD

**Issue by BetoReis** [orochasamuel/fiscalbr-net#42]

**Comment by orochasamuel** [comment]
Fala @BetoReis tudo na paz?

Não temos DEMO ainda mas você pode dar uma olhada nas classes de teste ou na issue https://github.com/orochasamuel/fiscalbr.net/issues/41, lá você vai ver um exemplo rápido de como criar o arquivo.

A escrita é bem simples, basta usar o método `EscreverCamposSped.EscreverCampos(SEU_REGISTRO_SPED)` depois de popular as informações na classe que você deseja escrever.

Qualquer dúvida adicional é só mandar aqui.

Vida longa e próspera 🖖
