### ISSUE TITLE
Enum CodigoVersaoLeiaute

### ISSUE THREAD

**Issue by bruno-crr** [orochasamuel/fiscalbr-net#47]
Boa tarde, com a verão do Nuget, o enumerador CodigoVersaoLeiaute não está acessível.

**Comment by orochasamuel** [comment]
Fala @bruno-crr tudo na paz por aí?

A verificação por versão para geração do arquivo ainda não foi publicada no Nuget, vou tentar agilizar essa atualização lá pra que todos tenham a versão mais recente.

Passei a fazer uso desse enum na geração dos arquivos para verificar alterações nos layouts. Ainda não finalizei todos os mapeamentos.

Vou fazer alguns correções nos Enums essa semana pra não gerar quando não for informado na hora de popular as classes.

E após essa correções faz o publish no Nuget.

Vida longa e próspera 🖖

**Comment by bruno-crr** [comment]
tudo bem obrigado!

**Comment by orochasamuel** [comment]
@bruno-crr os pacotes Nuget foram atualizados.
