### ISSUE TITLE
Reg 0220 Layout 16

### ISSUE THREAD

**Issue by bruno-crr** [orochasamuel/fiscalbr-net#48]
Boa tarde, na versao 16 foi adicionado um campo opcional no 0220 ref ao codigo de barras, o arquivo está com erro na estrutura por conta da qtd de campos.

**Comment by orochasamuel** [comment]
Fala @bruno-crr blz?

Irei fazer o publish para o Nuget neste final de semana.

Retorno com o aviso nesta issue.

Vida longa e próspera 🖖

**Comment by bruno-crr** [comment]
Opa tranquilo Obrigado pela atenção

**Comment by orochasamuel** [comment]
Pacotes nuget atualizados o/
