### ISSUE TITLE
Dúvida iniciante

### ISSUE THREAD

**Issue by RaCastroBR** [orochasamuel/fiscalbr-net#52]
Boa noite.

Acabei de descobrir o projeto e achei bastante interessante, porém, não achei uma documentação de como utilizá-lo em minha solution. Poderia fornecer ou indicar onde acho alguns exemplos de utilização?

Obrigado

**Comment by RaCastroBR** [comment]
Consegui utilizar aqui e vi que realmente vai ser bastante útil para o que eu vou precisar.
A minha necessidade é ler um arquivo do SPED ICMS e Contribuições, fazer algumas modificações, incluindo, excluindo e alterando registros e gerar um novo arquivo.

Em um teste rápido que fiz com a EFD Contribuições já consegui incluir alguns novos registros, porém, percebi que o arquivo resultante gerou em alguns campos de valor, que originalmente estavam em branco, com o valor 0 (zero). Isso pode ser parametrizado?

Outra coisa, o arquivo gerado perdeu a informação da Inscrição Municipal do registro 0140 (campo 09). Isso já havia sido identificado?

OBS: Estou usando via NUGET

Obrigado

**Comment by RaCastroBR** [comment]
Será que isto da Inscrição Municipal está acontecendo pois o campo está definido com tamanho 0?

![image](https://user-images.githubusercontent.com/83226821/157781933-8b75d6a7-a99e-4f01-a2e8-8e41932b7838.png)

**Comment by orochasamuel** [comment]
Fala @RaCastroBR tudo na paz?

É exatamente essa a causa da ausência da informação.

Vou fazer a correção hoje a noite e vou atualizar o NuGet.

Há outras implementações que foram feitas que ainda não estão na instalação via NuGet.

Vida longa e próspera 🖖

**Comment by orochasamuel** [comment]
Pacotes nuget atualizados o/
