### ISSUE TITLE
Duvida - SINTEGRA 

### ISSUE THREAD

**Issue by marceloxavier9644** [orochasamuel/fiscalbr-net#54]
Olá, tem algum exemplo de como gerar sintegra? 

Em MG ainda utilizamos sintegra e estou precisando muito, obg.

**Comment by FabioDlink** [comment]
@marceloxavier9644 conseguiu gerar o Sintegra. Tem algum exemplo?

**Comment by marceloxavier9644** [comment]
Aprendi como gerar, nao testei tudo pq meu sistema está em desenvolvimento ainda.

**Comment by FabioDlink** [comment]
Conseguir aqui. Tudo certo. Obrigado.

**Comment by marceloxavier9644** [comment]
@FabioDlink como vc gerou o registro 90 ? nao estou conseguindo escrever ele.

**Comment by orochasamuel** [comment]
@marceloxavier9644 tudo na paz?

O Registro 90 do SINTEGRA é o único registro que o FiscalBR gera "automagicamente", você só precisar informar as linhas previamente geradas.

Na geração do Registro 90 eu verifico quais registros estão no arquivo para totalizar as linhas de cada registro.

![image](https://user-images.githubusercontent.com/15462690/172029808-72cd5c2c-1caf-442f-be1c-cdad89d8dbbf.png)

Após instanciar a classe use o método `EscreverRegistro90`.

Vida longa e próspera 🖖

**Comment by devcristopher** [comment]
@orochasamuel bom dia, beleza?
Consegue me ajudar? 

Populei todos os registros, agora para gerar o arquivo eu preciso popular o R90 conforme sua resposta ali em cima? Como eu passo os registros que populei se o parametro é uma lista de string?

**Comment by orochasamuel** [comment]
Fala @devcristopher tudo na paz?

Imagino que você populou todos os registros e já está no final do seu método de geração agora, basta escrever as linhas para uma lista de strings e fazer a chamada do método.

**Comment by devcristopher** [comment]
Certo... eu populei, por exemplo, o registro 10: 
```
var registro10 = new Registro10(empresa.CnpjCpf, empresa.IE,empresa.RazaoSocial, empresa.Cidade,
 empresa.Estado, empresa.Telefone, model.DataInicio, model.DataFinal,  (CodFinalidadeArquivo)model.Finalidade, (CodEstruturaArquivo)model.ConvenioIcms, (CodNaturezaOperacoes)model.Operacao);
 ```
 
 Então criou-se o objeto de Registro10, esse registro que é a ''linha'' e que devo converter json/string?

**Comment by orochasamuel** [comment]
@devcristopher depois de instanciar o Registro90 você precisar chamar o método de escrita.

```cs

            var linhas = new List<string>();

            var source = new FiscalBr.Sintegra.Registro10(
                "00000000000191",
                "123456789",
                "BANCO DO BRASIL S.A.",
                "",
                "",
                "",
                initialDate,
                finalDate,
                FiscalBr.Sintegra.CodFinalidadeArquivo.Cod1,
                FiscalBr.Sintegra.CodEstruturaArquivo.Cod3,
                FiscalBr.Sintegra.CodNaturezaOperacoes.Cod3
                );

            var linhaEscrita = Common.Sintegra.EscreverCamposSintegra.EscreverCampos(source);

            linhas.Add(linhaEscrita);

            var reg90 = new FiscalBr.Sintegra.Registro90(
                "CNPJ",
                "IE",
                linhas
                );

            var reg90Escrito = reg90.EscreverRegistro90();

            // Adiciona Registro 90 escrito nas linhas
            linhas.Add(reg90Escrito);

```

As linhas passadas como parâmetro do construtor já devem ser todas as outras linhas do arquivo, após instanciar o R90 chame o método `EscreverRegistro90` e adicione o resultado nas linhas e salve no arquivo, exporte, dê o tratamento que desejar.

Tente desta forma e me retorne qualquer dúvida.

Vida longa e próspera 🖖

**Comment by devcristopher** [comment]
@orochasamuel 
Entendi! Muito obrigado, deu certo.

**Comment by orochasamuel** [comment]
De nada ✌️
