### ISSUE TITLE
Informação

### ISSUE THREAD

**Issue by candinho1987** [orochasamuel/fiscalbr-net#55]
Bom dia!
Seria possivel inserir os campos c170 em um arquivo sped sem eles com base em outro arquivo sped onde tem o c170, inserindo conforme o nomero da nota/cupom.
**Ambiente**
 - Layout: [exemplo: SPED Fiscal]
 - Versão .NET [.NET6]
 - Versão da Lib [NuGet]

**Comment by orochasamuel** [comment]
Fala @candinho1987 tudo na paz?

Você quer gerar os registros C170 em um arquivo com base na leitura de outro arquivo TXT?

Se eu entendi corretamente você pode fazer a leitura do primeiro arquivo (origem), após a leitura e as classes "populadas" com as informações você pode criar uma nova instância da classe do arquivo e fazer um `foreach`, e ir escrevendo no novo arquivo (destino). 

Vida longa e próspera 🖖

**Comment by orochasamuel** [comment]
Entendi, a ideia é boa.

Vou preparar um exemplo e te envio ainda hoje. 

Vida longa e próspera 🖖

**Comment by candinho1987** [comment]
> Entendi, a ideia é boa.
> 
> Vou preparar um exemplo e te envio ainda hoje.
> 
> Vida longa e próspera 🖖

Muito obrigado fico realmente muito feliz!

**Comment by candinho1987** [comment]
> 

no caso consigo gerar um novo sped completo ne, tipo no arquivo original nao tem o c170 e no segundo tem o c170 mas nao esta corrigido, no caso quero pegar os dados do bloco c170 do segundo e inserir no primeiro

**Comment by orochasamuel** [comment]
Sim, é possível fazer.

**Comment by candinho1987** [comment]
Boa noite! da uma olhada se estou no caminho certo.
```
var arquivo = fd2.FileName;
                var sped = new ArquivoEFDFiscal();
                sped.Ler(arquivo);
                var blococ = sped.BlocoC.ToString();
                gridSped.DataSource = blococ;
```
neste caso queria abrir o arquivo e visualizar as informação em um datagridview para saber se de fato leu o arquivo.
Mas me apresentou um erro
`'Object of type 'System.String' cannot be converted to type 'System.Nullable`1[FiscalBr.Common.IndPeriodoApuracaoIpi]'.'`

**Comment by candinho1987** [comment]
Meu arquivo esta na versao 15, nao testei na versao 16

**Comment by orochasamuel** [comment]
Dá uma olhada nesse exemplo @candinho1987 e veja se te ajuda.

```cs

    public class LerArquivoCandinho1987
    {
        [Fact]
        public void LerArquivoSpedFiscal()
        {
            List<string> lines = new List<string>();
            var filePath = @"C:\source.txt";

            // Origem
            var spedFile1 = new ArquivoEFDFiscal();

            spedFile1.Ler(filePath);

            var spedFile2OnlyC170s = new List<EFDFiscal.BlocoC.RegistroC170>();

            for (int i = 0; i < spedFile1.BlocoC.RegC001.RegC100s.Count; i++)
            {
                for (int j = 0; j < spedFile1.BlocoC.RegC001.RegC100s[i].RegC170s.Count; j++)
                {
                    var currentItem = spedFile1.BlocoC.RegC001.RegC100s[i].RegC170s[j];

                    var newC170 = new EFDFiscal.BlocoC.RegistroC170();

                    /*
                     * Preenche os campos desejados
                     */

                    newC170.Cfop = currentItem.Cfop;

                    /*
                     * Insere na lista de registros
                     */

                    spedFile2OnlyC170s.Add(newC170);
                }
            }

            /*
             * Gera a linha
             */

            foreach (var item in spedFile2OnlyC170s)
            {
               lines.Add(Common.Sped.EscreverCamposSped.EscreverCampos(item));
            }

            /*
             * Inclui as linhas no novo arquivo
             */

            //[...]
        }
    }

```

Dá uma olhada nas issues https://github.com/orochasamuel/fiscalbr-net/issues/37 e https://github.com/orochasamuel/fiscalbr-net/issues/41.

A issue 37 trata da correção do erro relatado acima. E a issue 41 trata de exemplos de como gerar o arquivo.

Vida longa e próspera. 🖖
