### ISSUE TITLE
EFD contribuição erro reg c 500

### ISSUE THREAD

**Issue by EttorePaludeto** [orochasamuel/fiscalbr-net#56]
E ae, salve, salve rapaziada!

Só pra avisar, foi incluído um 15 campo no Registro C 500 do EDF Contribuições.

Não entendi direito a ideia do campo, mas eh uma CHAVE DE NFE.

Amanhã eu pesquiso melhor e complemento a issue.

Abrax!!!

**Comment by orochasamuel** [comment]
Fala @EttorePaludeto tudo na paz?

Foi incluido no layout para identificar créditos de energia elétrica. O modelo 66 é o novo modelo para notas de energia elétrica, alguns contribuintes industriais fazem tomada de crédito mensal destas notas, nos estados onde a SEFAZ permite. Já em outros estados esse crédito deve ser tomado mediante processo tributário administrativo.

O modelo 55 foi incluído pois acredito que a intenção do fisco futuramente é permitir alguma operação relacionada à energia fotovoltaica, nos casos em que aconteça devolução para a rede elétrica, por exemplo. O NCM de energia elétrica é o 2716.00.00.

![image](https://user-images.githubusercontent.com/15462690/171272047-1ecc816a-731d-46c4-a128-9b5e6940c157.png)
