### ISSUE TITLE
Registro 0205: Descrição anterior  do item sempre vazia

### ISSUE THREAD

**Issue by davi-barboza** [orochasamuel/fiscalbr-net#58]
**Descreva o erro**
No registro "0205" campo "CodAntItem", esta sendo feita a atribuição da descrição anterior do item, porém ao gerar o arquivo .txt o mesmo sempre fica vazio

**Comportamento esperado**
Preenchimento correto do campo

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/67708096/178997631-c162cdd0-66d6-454a-b8e0-68bb89301271.png)

**Informações adicionais**
Imagino que possa ter algo a ver com o tamanho do campo que esta zerado
![image](https://user-images.githubusercontent.com/67708096/178998124-b01d66aa-ac03-47fc-bd90-6e05b69d9d78.png)

**Comment by orochasamuel** [comment]
Fala @davi-barboza tudo na paz?

Correção feita no commit 2779a777d239191f0faef3754457a8c09ba67554.

Vida longa e próspera 🖖

**Comment by davi-barboza** [comment]
Obrigado querido, tmj.
