### ISSUE TITLE
Atualização do package

### ISSUE THREAD

**Issue by davi-barboza** [orochasamuel/fiscalbr-net#59]
O ultimo commit não está sincronizado com o pacote NuGet no Visual Studio.
Teria alguma previsão para essa atualização?

**Comment by davi-barboza** [comment]
Não foi necessário, gerei as dlls.

**Comment by orochasamuel** [comment]
Fala @davi-barboza está pendente de alguns testes só antes de gerar o novo pacote do Nuget. Mas pelas DLLs vai funcionar beleza.
