### ISSUE TITLE
Preencher List do Resgistro0100

### ISSUE THREAD

**Issue by nelsonasousa** [orochasamuel/fiscalbr-net#63]
Boa noite,
Estou iniciando no uso da FiscalBr para geração do SPED, e, estou utilizando C#.

Ao fazer o Add() está me retornando o erro:
{"Referência de objeto não definida para uma instância de um objeto."}
Como se eu não tivesse declarado o objeto _Registro0001, sendo que já utilizei no Registro0005 e carregou normal.
Eu declarei errado?
Podem me dar uma ajuda?

Meu código:

` Bloco0.Registro0001 _Registro0001 = new Bloco0.Registro0001();`
` var _reg100 = new Bloco0.Registro0100 {
                            Reg = "0100",
                            Nome = "Contador",
                            Cnpj = "",
                            Cpf = "000000",
                            Crc = "000000",
                            Email = TxtEmailContador.Text,
                            CodMun = empresa.IdCidade
                        };`
`resultado = EscreverCamposSped.EscreverCampos(_Registro0100, false);`
 `                       linhas.Add(resultado);`
  `                      iLinhasBloco0100++;`
  `                      _Registro0001.Reg0100s.Add(_reg100);`

**Comment by orochasamuel** [comment]
Fala @nelsonasousa tudo na paz?

Dá uma olhada nessa issue https://github.com/orochasamuel/fiscalbr-net/issues/41 que tem exemplos de como gerar o arquivo.

Vida longa e próspera. 🖖

**Comment by nelsonasousa** [comment]
Olá @orochasamuel ,
 Obrigado pela resposta.
Eu estou com problemas pra preencher mais de um contador no registro 100. Poderia me dar uma luz?

**Comment by orochasamuel** [comment]
@nelsonasousa na issue https://github.com/orochasamuel/fiscalbr-net/issues/41 tem um exemplo prático de criação.

Mas no caso específico do 0100, só pode existir um registro deste tipo no arquivo.

![image](https://user-images.githubusercontent.com/15462690/208779113-52d5d77f-5c20-47f2-b842-10371e706deb.png)

Qual arquivo você está tentando gerar? ICMS ou CONTRIBUIÇÕES?

Só um contabilista pode ser o titular coresponsável pelas informações.

Vida longa e próspera 🖖

**Comment by nelsonasousa** [comment]
> @nelsonasousa na issue #41 tem um exemplo prático de criação.
> 
> Mas no caso específico do 0100, só pode existir um registro deste tipo no arquivo.
> 
> ![image](https://user-images.githubusercontent.com/15462690/208779113-52d5d77f-5c20-47f2-b842-10371e706deb.png)
> 
> Qual arquivo você está tentando gerar? ICMS ou CONTRIBUIÇÕES?
> 
> Só um contabilista pode ser o titular coresponsável pelas informações.
> 
> Vida longa e próspera 🖖

@orochasamuel ,
Obrigado pela resposta.
Estou tentando gerar o ICMS.
Sim, acabei vendo no manual que era apenas um.
Me confundi porque tem uma list<> do 100 declarada lá.
