### ISSUE TITLE
Formatação decimal cultura invariant

### ISSUE THREAD

**Issue by WalissonPires** [orochasamuel/fiscalbr-net#64]
**Descreva o erro**
Ao usar a biblioteca com a aplicação usando a cultura invariant a substiuição de caracters de separação de casas decimais e casas de milhares não funcionam como esperado.

Ao formatar o valor 0M para escrever no arquivo usando a cultura invariant fica "0.00". E o método EscreverCamposSintegra.EscreverCampos.cs:76 da uma replace somente em virgula. Assim o ponto é escrito para o arquivo tornando-o inválido. Já a formatação de valores diferentes de zero também dão uma replace no ponto (Entendo o motivo. Já que zero nunca teria o ponto).

Saída na cultura invariant: 
`5400   0000000000   000              0000000.000000000000.000000000000000000000000000000000000000000000000000000`
Saída na cultura PT-BR:
`5400   0000000000   000              000000000000000000000000000000000000000000000000000000000000000000000000000`

Acrescentar o replace do ponto na formatação do valor zero resolve o problema. Posso abrir um pull request?

OBS.: Eu sei que eu poderia mudar a cultura para PT-BR antes da execução do método. Mas gosteria de não ter que fazer isso. Sem falar que isso fez eu perdi alguns horas tentando descobrir o problema. Essa alteração ajudaria outros não ter que passar por isso  :)

**Comment by orochasamuel** [comment]
Fala @WalissonPires tudo na paz?

Obrigado por ter investigado o problema. Pode abrir um pull sim que eu aprovo aqui.

Você está tentando gerar Sintegra para qual UF? São poucas que não aderiram ao SPED.

Vida longa e próspera. 🖖

**Comment by WalissonPires** [comment]
Desculpe pela demora. O PR #73 não resolveu o problema. O problema que informei e somente na formatação do valor zero e no Sintegra. Abri o PR #77 com a correção.

E sobre sua pergunta sobre em qual estado estamos gerando o sintegra. Na verdade estamos fazendo um sistema para atender todo o brasil. Então por isso implementamos o Sintegra.

**Comment by orochasamuel** [comment]
Fala @WalissonPires

Tudo na paz?

Fiz a aprovação do PR agora a pouco.

Vida longa e próspera 🖖
