### ISSUE TITLE
[DUVIDA] Bloco C180

### ISSUE THREAD

**Issue by kailonalexandre** [orochasamuel/fiscalbr-net#65]
Estou tentando criar o bloco C180 porem não estou achando um meio de acessa-lo no fim do bloco para adiciona-lo ao Arquivo.

Tentei chamar pelo blocoC porem ele só me trás as listas do bloco C185.

Desde já agradeço a atenção.

**Comment by orochasamuel** [comment]
Fala @kailonalexandre tudo na paz?

Conseguiu criar o C180? Qualquer dúvida adicional é só postar aqui.
