### ISSUE TITLE
Registro C100 para modelo 65 (NFCe)

### ISSUE THREAD

**Issue by WandersonLSoft** [orochasamuel/fiscalbr-net#67]
Bom dia,
Ao preencher o objeto C100 para o modelo 65, fiz o tratamento para os campos onde o manual aponta o não preenchimento. São eles : 
COD_PART, VL_BC_ICMS_ST, VL_ICMS_ST, VL_IPI, VL_PIS, VL_COFINS, VL_PIS_ST e VL_COFINS_S.

Os campos  VL_BC_ICMS_ST, VL_ICMS_ST, mesmo não preenchendo ou setando como nothing, ao gerar o arquivo está preenchendo com zeros e o validador acusa o erro. 
Os demais, IPI, Pis e Cofins estão corretos, algo que não estou fazendo de forma correta ou precisa realmente de uma revisão? 

Obrigado pela atenção e parabéns pelo projeto.

**Comment by orochasamuel** [comment]
Fala @WandersonLSoft tudo na paz?

Qual versão você está usando? Nuget ou DLL?

Qual arquivo? EFD Contribuições ou EFD Fiscal?

Vida longa e próspera 🖖

**Comment by WandersonLSoft** [comment]
Bom dia, tudo em Paz.
Versão da dll 2.0.2.0 - 28/11/2022 10:56

Peço desculpas pelo transtorno. 
A falha foi minha ao escriturar o registro C190, minha aplicação estava zerando os valores do registro C100.
Realizei o tratamento para o modelo 65 e ficou certo. 

Mais uma vez, peço desculpa.
