### ISSUE TITLE
Compatibilizar versão da DLL com a versão do Layout

### ISSUE THREAD

**Issue by orochasamuel** [orochasamuel/fiscalbr-net#75]
Atualmente a versão do layout da EFD Fiscal é a 17, nos próximos commits vou alterar a versão da DLL para quando publicar no Nuget o package fique na mesma versão do layout.

Isso facilitará a identificação da versão de forma visual.

Caso tenham alterações e/ou correções de bugs na mesma versão usar o versionamento semântico:

17 (major) 1 (minor) 0 (patch) --> (aka 17.1.0)

MAJOR -> versão do layout, sofrerá alterações somente quando a versão do layout mudar

**Comment by WashingtonAutocom** [comment]
@orochasamuel Perfeito.
Na implementação da issue #66, nos PR, eu e a @ThalyaAutocom, não alteramos o versionamento justamente para que você decida o correto, seguindo esse padrão vai ser muito bom.

**Comment by orochasamuel** [comment]
Nuget atualizado
