### ISSUE TITLE
[BUG] - dll nuget parece incorreta. 

### ISSUE THREAD

**Issue by hbdbim** [orochasamuel/fiscalbr-net#85]
Estou utilizando a dll do nuget.

Esta dando null reference no metodo GetAttribute da classe MetodosAuxiliares.

Ao abrir a dll e olhar o metodo esta da seguinte forma
`private static T GetAttribute<T>(this Enum value) where T : Attribute
        {
            return (T)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(T), inherit: false)[0];
        }`

Enquanto o código não compilado esta assim:
`private static T GetAttribute<T>(this Enum value) where T : Attribute
        {
            var type = value.GetType();
            var memberInfo = type.GetMember(value.ToString());
            var attributes = memberInfo[0].GetCustomAttributes(typeof(T), false);
            return (T)attributes[0];
        }`

O codigo não compitalado esta funcionando.

Suspeito que tenha algo errado com a publicação.

**Comment by orochasamuel** [comment]
@hbdbim 

Esse método não sofreu nenhuma alteração desde sua implementação inicial em 15 de agosto de 2017 (na época a lib tinha outro nome [SPED.NET](https://github.com/AOPack/SPEDBr.NET/commit/455800920dc8a723f0ade65350d9d083b51b62c2#diff-4e39d9c3b76d60feb7d16891021089a3f13ee6df4d515c34113002018dd88e56)).

Qual Registro você está tentando gerar?

É EFD Contribuições OU EFD Fiscal?

Acredito que o problema não seja no método de "extração" dos valores enum, caso contrário já teríamos uma chuva de reclamações de vários outros devs.

Vida longa e próspera 🖖

**Comment by marcosgerene** [comment]
Baixei ontem o nuget em um projeto limpo para adicionar o bloco H em um SPED. Fiz a leitura, manutenção, recalculo do Bloco9 e escrevi o arquivo modificado sem problemas.

**Comment by hbdbim** [comment]
Descobri a causa do erro.
Eu nao estou preenchendo o campo IndDest do bloco C500 e na ultima versão ele deixou de ser nullable.
Mas acho que da pra tentar fazer alguma melhoria para apontar melhor o erro.

Faz um tratamento para apontar que o campo nao foi preenchido assim que é feito para os outros campos obrigatorios.

**Comment by orochasamuel** [comment]
@hbdbim se é ENUM e pode ser NULO o certo é incluir um "NONE" na lista de enums.

Atualmente o IndDest do C500 não tem. Vide abaixo:
![image](https://user-images.githubusercontent.com/15462690/223541594-65d1c2e5-7578-40b9-b2f7-50a7277ddc48.png)

Quando puder ser nulo eu incluo **NONE** como primeira opção.
![image](https://user-images.githubusercontent.com/15462690/223541927-c7fd72f4-9075-4ba1-98a1-6827f72b0075.png)

A primeira implementação foi citada na issue https://github.com/orochasamuel/fiscalbr-net/issues/37.

**Comment by orochasamuel** [comment]
@hbdbim fiz a alteração e no próximo commit já estará corrigido.

Inclui o ENUM em branco ("") pois nas operações de ENTRADA esse campo não deve ser informado.

**Comment by ThalyaAutocom** [comment]
> @hbdbim fiz a alteração e no próximo commit já estará corrigido.
> 
> Inclui o ENUM em branco ("") pois nas operações de ENTRADA esse campo não deve ser informado.
> 
> EDIT @hbdbim suas operação no C500 são de saída, certo?
> 
> Para saída esse campo de estar informado.
> 
> O jeito é incluir validações dentro de cada registro e no momento da geração o DEV ir coletando essas validações de layout. ![image](https://user-images.githubusercontent.com/15462690/223550454-303bda56-715b-4349-a52c-e7a21f0e3d69.png) PS: Para ser mais explicito a tipagem do retorno teria que ser string para facilitar o entendimento do erro. Esse tipo de implementação que vá alterar em larga escala a biblioteca eu prefiro abrir uma discussão e coletar opiniões da comunidade.
> 
> A lib já faz validações estruturais do arquivo na classe "EscreverCamposSped".


Boa tarde @orochasamuel. 
Você já gerou o pacote nuget com essa alteração? 
Instalei a versão mais atual no meu gerador, porém o enum "NONE" do registro C500 não aparece como opção para seleção.

**Comment by orochasamuel** [comment]
@ThalyaAutocom já sim.

Qual a propriedade você está tentando popular?

**Comment by ThalyaAutocom** [comment]
@orochasamuel seria o efdC500.IndDest mesmo. 
Vou reinstalar então, limpar o cache e tentar novamente. Mais tarde te dou um retorno.

**Comment by orochasamuel** [comment]
Opa!!

Passando para avisar que os novos pacotes Nuget já estão disponíveis. o/

Vida longa e próspera 🖖
