### ISSUE TITLE
Leitura SPED passando string com dados ao invés do caminho do arquivo

### ISSUE THREAD

**Issue by ze-resolveisso** [orochasamuel/fiscalbr-net#94]
Olá

Queria se fosse possível ter a opção de fazer a leitura dos dados do SPED passando uma string com o conteúdo ao invés de passar o caminho do arquivo

Desde já Agradeço
José Fernando

**Comment by orochasamuel** [comment]
@ze-resolveisso essa feature foi adicionada no commit https://github.com/orochasamuel/fiscalbr-net/commit/3ac02a7b293b00d4f2361ef3abaada7c56b98b27.

Ainda não está disponível no Nuget, e por hora, só contempla a leitura da EFD Fiscal.

Para usar a leitura direta basta usar o método `Ler` e passar o array de string como parâmetro.

```cs

var meuArquivoSped = new ArquivoEFDFiscal();

meuArquivoSped.Ler(MINHA_VARIAVEL_STRING_COM_AS_LINHAS);

meuArquivoSped.GerarLinhas();

```

**Comment by ze-resolveisso** [comment]
@orochasamuel inicialmente pretendia utilizar essa opção para a leitura do EFD Fiscal mesmo.

Vou aguardar ser disponibilizado no Nuget então para testar

Obrigado

**Comment by orochasamuel** [comment]
Opa!!

Passando para avisar que os novos pacotes Nuget já estão disponíveis. o/

Vida longa e próspera 🖖
