### ISSUE TITLE
[BUG] - ICMS/IPI - Registro G125 - Movimentação de bem ou componente do ativo imobilizado

### ISSUE THREAD

**Issue by alxmath** [orochasamuel/fiscalbr-net#95]
Olá,

Na geração do registro G125 (ICMS-IPI), percebi que a lib trunca para dois caracteres o campo COD_IND_BEM (código individualizado do bem ou componente). No meu caso, tenho um item de ativo imobilizado cujo COD_IND_BEM é 28034, porém, a lib escritura esse código truncando o seu valor para 28. Como esse item foi escriturado com o código certo (28034) no registro 0300 (bens/componentes do ativo imobilizado), o PVA emite dois erros para esse item.

![Captura de tela 2023-06-15 085117](https://github.com/orochasamuel/fiscalbr-net/assets/37917022/f18bbe17-4009-4adf-846e-3d91cda62604)

Ambiente:
 - Layout: 17
 - NET 6
 - Versão da Lib: 17.01 (Nuget)

Olhei o código da lib e reparei que para o registro G125, o atributo para propriedade CodIndBem está configurada para ter o tamanho   de dois caracteres:

![Captura de tela 2023-06-15 085820](https://github.com/orochasamuel/fiscalbr-net/assets/37917022/0277b45e-32be-4b58-a6bc-97d85d46a426)

**Comment by orochasamuel** [comment]
Opa!!

Passando para avisar que os novos pacotes Nuget já estão disponíveis. o/

Vida longa e próspera 🖖
