### ISSUE TITLE
[BUG] Indicadores de Frete

### ISSUE THREAD

**Issue by adrbarros** [orochasamuel/fiscalbr-net#98]
Adicionado 2 valores no Pull Request #96 
3 - Transporte Próprio por conta do Remetente;
4 - Transporte Próprio por conta do Destinatário;

Se possível, revisar para ver se esta tudo OK

**Comment by orochasamuel** [comment]
Fala @adrbarros tudo na paz?

Adicionei os novos enumeradores todavia, mantive os antigos para assegurar a retro compatibilidade na leitura ou geração retroativa.

```cs

public enum IndTipoFrete
{
    [DefaultValue("")] None = -1,

    [DefaultValue("0")] ContaRemetenteCif = 0,
    [DefaultValue("1")] ContaDestinatarioFob = 1,
    [DefaultValue("2")] ContaTerceiros = 2,
    [DefaultValue("3")] ContaProprioRemetente = 3,
    [DefaultValue("4")] ContaProprioDestinatario = 4,

    [DefaultValue("9")] SemCobrancaFrete = 9,

    [DefaultValue("0")] ContaTerceirosPre2012 = 120,
    [DefaultValue("1")] ContaEmitentePre2012 = 121,
    [DefaultValue("2")] ContaDestinatarioPre2012 = 122,

    [DefaultValue("0")] ContaEmitentePre2018 = 180,
    [DefaultValue("1")] ContaDestinatarioRemetentePre2018 = 181,
    [DefaultValue("2")] ContaTerceirosPre2018 = 182
}

```

**Comment by adrbarros** [comment]
@orochasamuel, tudo em paz (Sempre na Correria), e por ai?
Muito Obrigado por aceitar o PullRequest

**Comment by orochasamuel** [comment]
Opa!!

Passando para avisar que os novos pacotes Nuget já estão disponíveis. o/

Vida longa e próspera 🖖
