### ISSUE TITLE
[BUG] Registros F120 e F130

### ISSUE THREAD

**Issue by WandersonLSoft** [orochasamuel/fiscalbr-net#99]
Estou gerando o sped contribuições e o registro F120 estava preenchendo o objeto, mas não estava gerando essa linha no arquivo. 

Percebi que esse bloco F120 e o F130, os campos de valores numéricos estão dessa forma no código:
Os valores numéricos estão como string, estou citando este campo, mas os demais estão da mesma forma.

            /// <summary>
            ///   Valor de Aquisição dos Bens Incorporados ao Ativo Imobilizado –Crédito com base no valor de aquisição.
            /// </summary>
            [SpedCampos(7, "VL_OPER_AQUIS", "N", 0, 2, true, 2)]
            public string VlOperAquis { get; set; }

**Comment by orochasamuel** [comment]
Fala @WandersonLSoft tudo na paz?

Obrigado por avisar, há alguns registros menos usados que necessitam de uma revisão, principalmente nos tipos primitivos.

As correções estão no commit https://github.com/orochasamuel/fiscalbr-net/commit/422b0f6882a8c4c06f4c5ccb5ff6c14ed27a95a6.

Qualquer dúvida é só avisar.

Vida longa e próspera 🖖

**Comment by orochasamuel** [comment]
Opa!!

Passando para avisar que os novos pacotes Nuget já estão disponíveis. o/

Vida longa e próspera 🖖
